ios/VibeTunnelTests/PerformanceTests.swift, web/README.md, web/src/client/components/session-view.test.ts, web/src/client/components/session-view.ts, web/src/client/components/session-view/session-header.ts, web/src/client/components/terminal.test.ts, web/src/client/components/terminal.ts, web/src/client/utils/path-utils.ts, web/src/server/pty/pty-manager.ts, web/src/server/routes/sessions.ts, web/src/shared/types.ts, web/src/test/e2e/sessions-api.e2e.test.ts
- Implements automatic width limiting based on initial session dimensions
- Prevents browser terminal from exceeding native terminal width by default
- Allows manual override through width selector for users who want wider terminals
- **NEW**: Shows "≤120" in the UI to indicate width is limited by session dimensions
When switching to the VibeTunnel browser session while Claude code is actively running and producing high log volumes, the native terminal experiences flickering. This is caused by the browser terminal automatically expanding to full width, which exceeds the native terminal's capabilities.
The browser terminal now respects the initial terminal width (120 cols by default) as a maximum limit. This prevents overflow while still allowing:
- Automatic width reduction for mobile …
=> Fix terminal width overflow causing flickering in native terminals

web/src/client/app.ts, web/src/client/components/session-card.test.ts, web/src/client/components/session-view.ts, web/src/client/services/auth-client.ts, web/src/client/utils/logger.test.ts, web/src/client/utils/logger.ts
- Fixed frontend logs not streaming to server in no-auth mode
- Replaced console.log calls with logger throughout the codebase
- Added comprehensive test coverage for logger functionality
Frontend logs were not being sent to the server because the logger was checking for authentication and skipping log sending when no auth token was present. This prevented logs from working in no-auth mode.
- Updated frontend logger to check `/api/auth/config` for no-auth mode
- When no-auth mode is enabled, logs are sent without authentication headers
- Maintains backward compatibility for authenticated mode
- `web/src/client/utils/logger.ts`: Added no-auth mode detection
- `web/src/client/app.ts`: Replaced 19 console calls with logger
- `web/src/client/services/auth-client.ts`: Replaced 16 console calls …
=> Fix frontend log streaming in no-auth mode

mac/scripts/build-web-frontend.sh
- Add `filter_build_output()` function to build script to remove common non-actionable warnings
- Apply filtering to all pnpm commands to reduce build log noise while preserving important errors
- Deprecated API warnings from Node.js native modules 
- Xcode C++ warnings about field initializers
- npm configuration warnings
- Tailwind CSS glob pattern warnings  
- gyp build information messages
The macOS build process was generating hundreds of warnings from third-party dependencies and build tools that developers can't fix. This noise made it difficult to spot actual issues in the build output.
=> feat: Add build output filtering to remove non-actionable warnings

.github/workflows/mac.yml, docs/development.md, mac/VibeTunnel/vt, mac/scripts/test-pr132-fix.sh, mac/scripts/test-vt-aliases.sh, mac/scripts/test-vt-integration.sh, web/src/client/utils/logger.test.ts, web/src/server/fwd.ts, web/src/test/unit/fwd-argument-parsing.test.ts
Fixes #101 - Restores alias functionality in the vt command by removing double shell-wrapping
- Remove -- separator from resolve_command function calls in vt script
- Fix regression that prevented aliases from working properly
- Add comprehensive test for ProcessUtils.resolveCommand behavior
- Update fwd.ts to properly handle -- as an argument separator
- Document vt CLI wrapper technical details in development guide
- ✅ Added unit test demonstrating the issue and verifying correct behavior
- ✅ Manually tested with aliases in Debug build
- ✅ All web tests pass (`pnpm run test`)
- ✅ Linting and type checking pass (`pnpm run lint && pnpm run typecheck`)
- ✅ Built and tested macOS app locally
The -- separator was causing ProcessUtils.resolveCommand to misinterpret the command array, with …
=> fix: remove double shell-wrapping for aliases in vt script

web/spec.md, web/src/server/services/stream-watcher.ts, web/src/server/utils/prompt-patterns.ts, web/src/test/fixtures/test-data.ts, web/src/test/unit/stream-pruning.test.ts
- Implement automatic detection of terminal clear sequences (ESC[3J)
- Prune asciinema streams to skip content before the last scrollback clear
- Preserve terminal dimensions from last resize before clear
- Add comprehensive tests including real-world Claude session data (4.9MB file)
- Optimize initial load time for long terminal sessions with clears
This significantly reduces the amount of data sent when replaying sessions that contain terminal clear operations. For example, a real Claude session with 6000+ events gets pruned to just the content after the last clear, improving performance for long-running sessions.
=> feat: add asciinema stream pruning for clear sequences

mac/VibeTunnel/Utilities/CLIInstaller.swift, mac/VibeTunnelTests/CLIInstallerTests.swift
- Fixed CLI installation verification to handle the updated vt script format
- The verification now checks for `exec "$VIBETUNNEL_BIN" fwd` without requiring exact argument matching
After tapping 'OK' on the "CLI Tools Installed Successfully" popup, the AdvancedSettingsView incorrectly showed the CLI tool as not installed, even though the installation was successful.
The `checkInstallationStatus()` method was checking for an exact string match:
```swift
content.contains("exec \"$VIBETUNNEL_BIN\" fwd \"$@\"")
```
However, the vt script was updated to include `$TITLE_MODE_ARGS`:
```bash
exec "$VIBETUNNEL_BIN" fwd $TITLE_MODE_ARGS "$@"
```
This mismatch caused the verification to fail.
Updated the verification to check only for the presence of `exec "$VIBETUNNEL_BIN" fwd`, making it …
=> fix: correct CLI installation verification after title mode args update

web/src/client/app.ts
✅ Problem: Navigating to non-existing sessions caused infinite "Waiting for session..." loading state
✅ Solution: Modified app.ts:364-377 to redirect to list view with proper error message after initial load completes
✅ Behavior Now:
1. URL: /?session=MISSING_SESSION
2. Shows brief initial loading during session fetch
3. Detects session doesn't exist after initialLoadComplete = true
4. Automatically redirects to list view showing existing sessions
Fixes a regression from acf91e228da049fa5787526a2b2ad0642effea6b
=> Fix an issue that caused missing sessions to not load

web/src/server/pty/pty-manager.ts, web/src/server/pty/types.ts
This PR fixes two critical race conditions in the terminal title injection logic:
1. **Lost title updates**: Titles were being lost when `pendingTitleToInject` was cleared before the async write operation executed
2. **Quiet period violations**: The injection timer was cleared before `lastWriteTimestamp` was updated, allowing new injections to start too soon
- Added `titleInjectionInProgress` flag to prevent concurrent injections
- Update `lastWriteTimestamp` immediately before enqueueing (not in async callback) to prevent quiet period violations  
- Clear `pendingTitleToInject` only after successful write completion
- Compare titles before clearing to avoid losing newer updates during the write
- Stop injection timer only when no pending titles remain
- Use try-finally to ensure …
=> Fix title injection race conditions

mac/VibeTunnel/vt
This PR enhances the `vt` script to display the path and version information of the vibetunnel binary at the bottom of the help menu.
- Added a new section at the bottom of the help output showing:
- Full path to the vibetunnel binary being used
- Version number (e.g., v1.0.0-beta.6)
- Build date and time
- Platform information (e.g., darwin/arm64)
- Enhanced the app discovery logic to include project build directories for development scenarios
```
VIBETUNNEL BINARY:
Path: /Users/steipete/Projects/vibetunnel/mac/build/Build/Products/Debug/VibeTunnel.app/Contents/Resources/vibetunnel
Version: v1.0.0-beta.6
Built: 2025-07-02T07:08:11+01:00
Platform: darwin/arm64
```
- Users can easily verify which VibeTunnel binary is being used
- Helpful for debugging version-related issues
- Developers …
=> Add vibetunnel binary path and version info to vt help

web/src/client/components/session-view/lifecycle-event-manager.ts
- Add focus management check in lifecycle keyboard handler
- Skip keyboard capture when overlays/modals are displayed
- Prevents keyboard conflicts with form inputs in overlays
=> fix: prevent keyboard capture when overlays are active

ios/VibeTunnel/Views/Sessions/SessionCardView.swift
We can now properly see the cards in the sessions list
=> SessionCardView: Fix initial brightness making the card invisible

mac/scripts/node-path-setup.sh
- Prioritize Homebrew node over NVM/system node for build reliability
- Add early exit when Homebrew node is found and working
- Disable auto-switching for fnm/NVM in CI/Xcode environments
- Add comprehensive error handling and fallback logic
- Fix issue #246 where NVM was overriding Homebrew node selection
Tested: Successfully switches from v24.2.0 to v24.3.0 during builds
=> fix: resolve Xcode Node.js detection issues with fnm/homebrew conflicts (#246)

.github/scripts/verify-release.sh, .gitignore, CHANGELOG.md, docs/homebrew-issue.md, mac/CHANGELOG.md, mac/VibeTunnel-Mac.xcodeproj/xcshareddata/xcschemes/VibeTunnel-Mac.xcscheme, mac/VibeTunnel/version.xcconfig, mac/scripts/build-web-frontend.sh, mac/scripts/check-xcode-settings.sh, mac/scripts/node-path-setup.sh, test-homebrew-fix.sh, verify-release-build.sh, web/build-custom-node.js, web/build-native.js, web/package.json
- Fixes "library not loaded" errors on systems without Homebrew installed
- Ensures vibetunnel binary only links to system libraries
- Addresses regression introduced between beta 6 and beta 7
The vibetunnel binary in beta 7 had dependencies on Homebrew libraries:
- `/opt/homebrew/opt/brotli/lib/libbrotlidec.1.dylib`
- `/opt/homebrew/opt/c-ares/lib/libcares.2.dylib`
- And 8 other Homebrew libraries
This caused the app to fail on systems without Homebrew with errors like:
```
dyld: Library not loaded: /opt/homebrew/opt/brotli/lib/libbrotlidec.1.dylib
Referenced from: /Applications/VibeTunnel.app/Contents/Resources/vibetunnel
Reason: image not found
```
Commit 826d8de4 introduced `node-path-setup.sh` which adds Homebrew paths to PATH with priority:
```bash
export …
```
=> Fix Homebrew library dependencies in release builds

mac/VibeTunnel/Core/Models/AppConstants.swift, mac/VibeTunnel/Core/Services/RepositoryDiscoveryService.swift, mac/VibeTunnel/Presentation/Components/NewSessionForm.swift, mac/VibeTunnelTests/RepositoryDiscoveryServiceTests.swift
This PR fixes several bugs identified in the repository discovery feature from PR #274:
1. **Session Form Loses Directory Preference** (mac/VibeTunnel/Presentation/Components/NewSessionForm.swift#L476-L487)
- The form was incorrectly loading the repository base path instead of the user's last selected working directory
- Fixed by restoring the proper preference loading behavior
2. **UserDefaults Handling Issues** (mac/VibeTunnel/Core/Models/AppConstants.swift#L53-L71)
- Removed circular dependency where repositoryBasePath would fall back to NewSession.workingDirectory
- Fixed bug where non-string UserDefaults values would return empty string instead of the default
- Changed default repository base path to ~/Development for better user experience
3. **Race Condition in Repository …
=> Fix bugs in repository discovery feature

web/src/server/utils/activity-detector.ts
- Removes the activity indicator (spinner/checkmark) from the terminal title display
- Keeps only the action text and statistics (duration, tokens)
- Prevents visual jumping in the terminal title when the indicator changes states
Modified `web/src/server/utils/activity-detector.ts`:
- Removed `${indicator}` from both display text formats (with and without token info)
- Updated comments to explain why indicators are excluded
=> Remove activity indicator to prevent title jumping

mac/VibeTunnel/Core/Models/AppConstants.swift, mac/VibeTunnel/Core/Services/BunServer.swift, mac/VibeTunnel/Core/Services/ControlPayloads.swift, mac/VibeTunnel/Core/Services/ControlProtocol.swift, mac/VibeTunnel/Core/Services/RepositoryPathSyncService.swift, mac/VibeTunnel/Core/Services/ServerManager.swift, mac/VibeTunnel/Core/Services/SystemControlHandler.swift, mac/VibeTunnel/Presentation/Views/Welcome/ProjectFolderPageView.swift, mac/VibeTunnel/Presentation/Views/WelcomeView.swift, mac/VibeTunnel/VibeTunnelApp.swift, mac/VibeTunnelTests/ModelTests.swift, mac/VibeTunnelTests/RepositoryPathSyncServiceTests.swift, mac/VibeTunnelTests/SystemControlHandlerTests.swift, mac/scripts/build.sh, web/src/client/components/unified-settings.test.ts, web/src/client/components/unified-settings.ts, web/src/server/routes/config.ts, web/src/server/server.test.ts, web/src/server/server.ts, web/src/server/websocket/control-unix-handler.ts, web/src/test/e2e/hq-mode.e2e.test.ts, web/src/test/e2e/logs-api.e2e.test.ts, web/src/test/e2e/resource-limits.e2e.test.ts, web/src/test/e2e/sessions-api.e2e.test.ts, web/src/test/integration/repository-path-sync.test.ts, web/src/test/unit/control-unix-handler.test.ts
This PR unifies the project folder synchronization between the Mac app and web UI, ensuring both interfaces always display the same current working directory.
1. **Mac → Web Sync**
- Added `RepositoryPathSyncService` to monitor repository path changes
- Sends path updates to web server via Unix socket
- Web UI automatically updates when Mac app changes directories
2. **Web → Mac Sync**  
- Added WebSocket endpoint `/ws/config` for configuration updates
- Web UI can send path updates back to Mac app
- Bidirectional synchronization ensures consistency
3. **UI Improvements**
- Added folder icon to session cards showing current directory
- Truncates long paths with ellipsis for better display
- Maintains visual consistency across both UIs
- Uses existing Unix socket infrastructure for Mac→Web …
=> Synchronize repository base path from Mac app to web UI

mac/VibeTunnel/Core/Services/WebRTCManager.swift
- Fixed WebRTC callbacks that were violating @MainActor constraints by running on WebRTC's signaling thread
- Added proper Task { @MainActor in ... } dispatch blocks to ensure continuation.resume() calls execute on main thread
- Addresses potential threading crashes in screen sharing functionality
The WebRTCManager is marked `@MainActor` but WebRTC completion handlers for `offer()`, `setLocalDescription()`, and `setRemoteDescription()` are called on WebRTC's internal signaling thread. Despite comments indicating the necessity to dispatch these callbacks to the main thread, the required `Task { @MainActor in ... }` blocks were missing.
This caused `continuation.resume()` calls to execute on the wrong thread, violating the @MainActor constraint and potentially causing crashes.
Wrapped each …
=> Fix WebRTC threading crash by dispatching callbacks to main thread

README.md, web/README.md, web/src/client/services/ssh-agent.ts
- Fixes SSH key generation/import failures when accessing VibeTunnel over HTTP from non-localhost addresses
- Adds clear error messaging explaining the Web Crypto API security restrictions
- Provides actionable solutions for users encountering this issue
Users accessing VibeTunnel from local network IPs (192.168.x.x, 10.x.x.x) over HTTP encounter "Cannot read properties of undefined (reading 'generateKey')" errors because browsers block the Web Crypto API on insecure origins.
1. Added comprehensive error detection in `ssh-agent.ts` that:
- Checks if Web Crypto API is available
- Detects local network IPs vs localhost
- Shows a user-friendly error banner with specific solutions
2. Added SSH troubleshooting section to README explaining:
- Why the issue occurs (browser security)
- Multiple …
=> Fix SSH key generation errors on non-localhost HTTP connections

web/.npmignore, web/docs/npm.md, web/scripts/postinstall-npm.js
**Resolves:** #380
Users installing VibeTunnel via npm on Ubuntu encountered two critical issues:
1. **PAM Authentication Warning**: "The native authenticate-pam module isn't found"
2. **npm_config_prefix Conflict**: Global npm installs failing with NVM due to environment variable
conflicts
- **PAM Module**: The `.npmignore` file excluded all `node_modules/` content, preventing the
`authenticate-pam` native module from being included in the npm package
- **npm_config_prefix**: Environment variable overrides NVM's per-version npm configuration, causing global
installs to fail or install to wrong locations
- **Fixed `.npmignore`**: Added exception `!node_modules/authenticate-pam/` to include the PAM module in
npm package
- **Impact**: Resolves authentication errors on Linux systems …
=> Fix PAM module and npm_config_prefix issues on Ubuntu

mac/VibeTunnel/Presentation/Views/Welcome/ProjectFolderPageView.swift, mac/VibeTunnel/Presentation/Views/WelcomeView.swift
- Resolves UI freezing when scanning home directory for Git repositories
- Implements background thread scanning with proper cancellation
- Only starts scanning when the project folder page is actually visible
1. **Background Scanning**: Moved the Git repository scanning to a background thread using Swift concurrency to prevent UI blocking
2. **Visibility-Based Scanning**: Only start scanning when ProjectFolderPageView becomes visible (page 4 of welcome flow), not when the entire WelcomeView loads
3. **Task Cancellation**: Added proper task cancellation handling to stop scanning when user navigates away from the page
4. **Performance Optimization**: Added cancellation checks during directory traversal to ensure responsive UI
Fixes #379
=> Fix welcome folder lag by implementing background scanning

mac/VibeTunnel/Core/Services/BunServer.swift, web/package.json, web/scripts/test-vt-syntax.sh, web/src/server/routes/sessions.test.ts, web/src/server/server.ts, web/src/test/fwd-test.ts, web/src/test/integration/vt-command.test.ts, web/src/test/unit/control-unix-handler.test.ts
Fixes #388 - Beta 11 broke the Mac app with "Error: ENOENT: no such file or directory, stat '/Applications/VibeTunnel.app/Contents/public/index.html'"
The issue was introduced in Beta 11 by npm package changes (PR #360) that added auto-detection logic for the public directory path. This logic failed when running from the Mac app bundle, causing the server to look for static files in the wrong location.
- Mac app now sets `BUILD_PUBLIC_PATH` environment variable pointing to the static files location
- Server checks `BUILD_PUBLIC_PATH` first before attempting auto-detection
- This ensures the Mac app bundle always finds its embedded web resources at the correct path
1. **BunServer.swift**: Added `BUILD_PUBLIC_PATH` environment variable that explicitly tells the server where to find the …
=> Fix missing public directory in Mac app bundle

.github/workflows/ci.yml, .github/workflows/ios.yml, .github/workflows/mac.yml, .github/workflows/node.yml, web/scripts/build-ci.js
This PR implements several CI performance optimizations to reduce build times by ~40%.
- Mac CI now downloads artifacts from Node.js CI instead of building web assets locally
- Added proper dependency so Mac CI waits for Node.js CI to complete
- Removed caching of the extremely large pnpm store
- Testing if fresh installs are actually faster than cache restore
- Mac CI now runs Xcode build, SwiftFormat, and SwiftLint in parallel
- Careful implementation to avoid Xcode conflicts
- Separated Swift package cache from derived data cache
- Better cache keys based on actual source files
- Added `HOMEBREW_NO_AUTO_UPDATE=1` to skip time-consuming updates
- Applied to both Mac and iOS workflows
- Added network and child concurrency limits for better performance
- Used `--prefer-offline` flag
- …
=> Optimize CI performance: remove duplicate web builds, parallelize tasks, improve caching

mac/VibeTunnel/Presentation/Views/Settings/CLIInstallationSection.swift, mac/VibeTunnel/Utilities/CLIInstaller.swift
- Implements uninstall functionality for the `vt` command line tool
- Adds a trash icon button in the settings dialog for easy uninstallation
- Closes #365
- **CLIInstaller.swift**: Added `uninstall()` and `uninstallCLITool()` methods with sudo authentication
- **CLIInstallationSection.swift**: Added trash icon button next to "VT installed" status
- Uninstalls from both standard paths: `/usr/local/bin/vt` and `/opt/homebrew/bin/vt`
- Shows confirmation dialog before uninstalling
- Displays appropriate success/error messages
The trash icon appears to the right of the "VT installed" status:
- Clean, minimal UI following macOS design conventions
- Red-colored trash icon with hover tooltip
- Available in both "installed" and "update available" states
=> Add uninstall option for vt command in settings

mac/VibeTunnel/Presentation/Views/Settings/DashboardSettingsView.swift
Please refer to the screenshot attached. I think this will be a useful feature to quickly open and verify if the ngrok tunnel is working, and also quickly copy and share the link.
Changes:
Before:
After:
- Replaced plain text ngrok URL with clickable Link component
- Showing full URL with https:// prefix instead of stripping it
- Added copy button with visual feedback (changes to checkmark when copied)
The ngrok URL in Settings → Dashboard → Remote Access section is now displayed as a blue clickable link that opens in the default browser, with a convenient copy button next to it.
=> feat(ui): make ngrok URL clickable with copy button in MacOS under Settings → Dashboard → Remote Access section

web/src/client/components/session-create-form.ts
- Fixed the new session dialog to have consistent dark mode styling
- Softened hard borders throughout the dialog using 50% opacity
- Fixed the terminal title mode picker that was showing in light mode colors
- Updated all borders to use `border-border/50` for softer appearance
- Fixed terminal title mode select dropdown to use dark theme colors (`bg-bg-tertiary`, `text-text`)
- Updated all text labels to use proper `text-text-muted` color tokens
- Made spawn window toggle and repository dropdown consistent with dark theme
- Updated quick start buttons to use softer borders and proper dark colors
- Fixed hover states to use appropriate dark theme colors
=> Fix new session dialog dark mode styling

docs.json
- Fixed Mintlify documentation generation by updating `docs.json` to use the correct navigation structure
- Resolved "Invalid docs.json" error that was preventing documentation from building
1. **Updated navigation structure**: Converted from legacy array format to the required `tabs`/`groups` object format
2. **Removed deprecated configuration**: Removed top-level `tabs` array that conflicted with new navigation structure
3. **Fixed file reference**: Added `.md` extension to GitHub Actions README reference
```
🚨 Invalid docs.json:
#.navigation: Invalid type. Field did not match any types in union
```
```
✓ preview ready
local   → http://localhost:3000
```
=> Fix Mintlify documentation generation

web/src/client/components/theme-toggle-icon.ts
- Extracted theme toggle improvements from PR #429
- Improved visual clarity of the theme toggle button
- Enhanced user experience with clearer tooltips
- **Updated system theme icon**: Replaced computer monitor icon with a half-light/half-dark circle design for better visual representation
- **Improved tooltip text**: System theme now shows as "Auto (System)" instead of just "System" for clearer communication
- **Consistent tooltip flow**: When cycling themes, the tooltip now shows "Auto" instead of "System" for the next state
This PR extracts only the theme toggle improvements from #429, separating them from the terminal focus functionality changes.
=> Improve theme toggle UI with better icon and tooltips

web/src/client/components/file-picker.ts, web/src/client/components/keyboard-capture-indicator.ts, web/src/client/components/session-view.ts, web/src/client/components/session-view/image-upload-menu.test.ts, web/src/client/components/session-view/image-upload-menu.ts, web/src/client/components/session-view/mobile-menu.ts, web/src/client/components/session-view/session-header.ts, web/src/shared/utils/time.test.ts
- Added a new image upload button to the session header with a dropdown menu
- Provides multiple ways to upload images: paste from clipboard, select files, camera capture, and browse files
- Fully accessible with keyboard navigation and responsive design
- Dropdown menu button positioned next to the file browser button
- Smart camera detection - only shows camera option on devices with cameras
- Follows existing UI patterns from mobile menu implementation
1. **📋 Paste from Clipboard** - Uses Clipboard API to paste images directly
2. **🖼️ Select Image** - Opens file picker with `accept="image/*"` filter
3. **📷 Camera** - Enables camera capture on mobile/camera-enabled devices
4. **📁 Browse Files** - Reuses existing file browser functionality
- Full keyboard navigation support (arrow keys, …
=> Add image upload menu with paste, select, camera, and browse options

web/src/client/components/file-browser.ts
- Fixed file selection in Git Changes mode to show file content immediately instead of diff
- Fixed View Diff/View File button functionality 
- Fixed issue where selecting a new file would show the previous file's content
- Always show file content by default when selecting files, not diff
- Clear previous file state (preview, diff, diffContent) when selecting a new file to prevent stale data
- Fix View Diff button to properly toggle between file and diff views
- Ensure diff content is checked along with diff data when rendering
1. Open file browser in Chrome
2. Enable "Git Changes" filter
3. Click on a modified file - it should show the file content immediately (not diff)
4. Click "View Diff" button - it should show the diff
5. Click "View File" button - it should go back to file content …
=> Fix file browser Git Changes mode behavior

web/src/client/components/unified-settings.ts
- Removes the restriction that prevented editing the repository base path on the web interface
- Enables two-way sync of repository path between web and Mac app
1. **Removed UI restrictions** - The repository path input field is no longer disabled/readonly when the server is configured
2. **Updated help text** - Now indicates that changes sync with the Mac app automatically
3. **Cleaned up unused code** - Removed the `isServerConfigured` property that was no longer needed
- The restriction was based on outdated assumptions about one-way sync
- The codebase already has a robust two-way sync architecture through file watchers
- Both Mac app and web server monitor `~/.vibetunnel/config.json` for changes
- Users should be able to edit the repository path from either interface
Before: Input …
=> Remove repository path edit restriction on web interface

mac/VibeTunnel/Core/Accessibility/AXElement.swift, mac/VibeTunnel/Core/Services/SystemPermissionManager.swift, mac/VibeTunnel/Core/Services/WindowTracking/WindowEnumerator.swift
- Replace CGWindowListCopyWindowInfo with Accessibility-only window tracking
- Eliminate screen recording permission dialog for better user experience
- Simplify permission model to only require Accessibility and AppleScript
1. **Added generic window enumeration to AXElement.swift**
- New `WindowInfo` struct to hold window data
- `enumerateWindows()` method with flexible filtering support
- Uses only Accessibility APIs - no screen recording permission needed
2. **Updated WindowEnumerator.swift**
- Replaced `CGWindowListCopyWindowInfo` with `AXElement.enumerateWindows()`
- Now uses only Accessibility APIs for window tracking
- Maintains same functionality without screen recording permission
3. **Removed screen recording permission code**
- Removed `ScreenCaptureKit` import
- Removed …
=> Remove screen recording permission requirement

web/src/client/components/session-list.test.ts
Added a specific test to verify that the session-killed event is properly re-dispatched from the session-list component to parent components with the correct payload (sessionId as a string).
This ensures the fix for the kill session button functionality is properly tested.
=> test: add test case for session-killed event re-dispatch

docs/cjk-ime-input.md, web/src/client/components/ime-input.ts, web/src/client/components/session-view.ts, web/src/client/components/session-view/input-manager.ts, web/src/client/components/session-view/interfaces.ts, web/src/client/components/session-view/lifecycle-event-manager.ts, web/src/client/utils/constants.ts, web/src/client/utils/ime-constants.ts
This PR introduces comprehensive support for Chinese, Japanese, and Korean (CJK) Input Method Editor (IME) on desktop browsers, addressing a critical need for international users working with terminal sessions.
- ✨ Added  component for transparent IME handling on desktop browsers
- 🎯 Uses invisible 1px input element that follows terminal cursor position (with fallback positioning)
- 🔧 Implements proper  constant instead of hardcoded values
- 🌐 Supports IME composition events (compositionstart/update/end)
- 📋 Includes global paste handling for better UX
- 🔒 Adds focus retention mechanism to prevent IME disruption
- 📱 Mobile devices continue using native virtual keyboard (no changes)
- The IME input element is completely invisible to users
- Positioned dynamically at terminal cursor …
=> feat: add CJK IME input support with improved Z-index management

mac/VibeTunnel/Core/Services/ServerManager.swift
Clean up unused ScreenCaptureKit dependency that was intended to be removed as part of https://github.com/amantus-ai/vibetunnel/pull/451
=> chore: Remove unused ScreenCaptureKit import from ServerManager

web/src/client/components/vibe-terminal-buffer.ts, web/src/client/styles.css, web/src/client/utils/terminal-renderer.ts
- Fixed the missing blinking cursor in binary terminal mode
- Cursor now properly blinks with green color like in standard terminals
1. **Removed inline style override**: The terminal renderer was setting an inline `background-color` that prevented the CSS animation from working
2. **Fixed cursor position calculation**: Removed client-side viewport truncation that was causing incorrect cursor position mapping
3. **Added session status check**: Cursor only shows when session is "running", not when exited
4. **Updated cursor CSS**: Made cursor more visible with green color (#23d18b) and proper blinking animation
The server already sends only the visible terminal area (terminal.rows worth of lines), but the client was doing additional truncation which caused the cursor position to be …
=> Fix blinking cursor in binary terminal mode

web/src/server/pty/asciinema-writer.ts, web/src/test/playwright/specs/terminal-basic.spec.ts, web/src/test/unit/asciinema-writer.test.ts
- Fixed position validation errors in AsciinemaWriter where actual file size was significantly larger than expected
- Improved test isolation to prevent file conflicts between parallel tests
- Made position validation more robust with proper async handling
The AsciinemaWriter tests were failing with position mismatches showing actual file sizes of 10226023 bytes while expecting much smaller values. This was likely caused by:
- Race conditions in position validation
- Multiple tests potentially writing to the same file
- Validation running before all async writes completed
1. **Improved Write Queue Synchronization**: The `validateFilePosition` method now waits for the write queue to drain before validating
2. **Better Error Context**: Added file paths to error messages for easier debugging …
=> Fix AsciinemaWriter position validation mismatch
